platform :ios, "7.1"

pod 'SDWebImage', '~>3.7'
pod 'SVProgressHUD'
pod 'APAvatarImageView'
pod 'BeamMusicPlayerViewController'
pod 'Fabric'
pod 'Crashlytics'
pod 'LMDropdownView'
pod 'ReactiveCocoa', '2.1.8'
pod 'LinqToObjectiveC', '2.0.0'